Add gradle-wrapper.jar
The gradle-wrapper.jar was missing which caused the build to fail.

Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain